name: Deploy to Salesforce via PowerShell

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Psfdx
        shell: pwsh
        run: |
          git clone --depth=1 https://github.com/tonygward/psfdx.git ./psfdx
          ./psfdx/install.ps1
          Install-SalesforceCli

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.GMAIL_AUTH_URL }}" > auth.txt
          Connect-SalesforceAuthUrl -SfdxUrlFile $auth.txt -SetDefault
          Get-SalesforceTargetOrg

      # - name: Authenticate to Salesforce
      #   run: |
      #     echo "${{ secrets.GMAIL_AUTH_URL }}" > auth.txt
      #     ./scripts/cicd/auth/login.sh auth.txt gmail

      # - name: Deploy
      #   run: sf project deploy start --source-dir force-app --wait 10

      # - name: Test Apex
      #   run: ./scripts/cicd/tests/apex/test-project.sh

      # - name: Fail if code coverage < 75%
      #   run: ./scripts/cicd/tests/apex/check-code-coverage.sh

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: apex-test-artifacts
      #     path: |
      #       test-results/**
      #       coverage/**